nginx-proxy:
    image: 'jwilder/nginx-proxy'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    container_name: nginx-proxy

phpweb:
    image: 'sixbyte/phpweb'
    links:
      - "mysql:mysqldocker"
      - "redis:redisdocker"
    volumes:
      - ./www:/var/www:rw
      - ./www/phpweb.local.conf:/etc/nginx/conf.d/phpweb.local.conf
    environment:
      - VIRTUAL_HOST=phpweb.local
    container_name: phpweb

mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    container_name: mysql

redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    container_name: redis